apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: aegis-system

helmCharts:
  - name: aegis
    includeCRDs: true
    valuesFile: values-prod.yaml
    releaseName: aegis-prod
    version: 0.1.0
    repo: https://markdavidmc0.github.io/aegis-mcp-control-plane/charts
