apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: aegis-local

helmCharts:
  - name: aegis
    includeCRDs: true
    valuesFile: values-kind.yaml
    releaseName: aegis-kind
    version: 0.1.0
    repo: https://markdavidmc0.github.io/aegis-mcp-control-plane/charts
